TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 2.0
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1

  meter_scoring: true
  pdist_scale: 3.5
  sim_time: 1.5

  holonomic_robot: false
