global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 20.0
   publish_frequency: 5.0
   width: 8.0
   height: 8.0
   resolution: 0.1
   static_map: true
   rolling_window: false
